export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS'
export const GET_ALL_CHARACTERS_PENDING = 'GET_ALL_CHARACTERS_PENDING'
export const GET_ALL_CHARACTERS_FULFILLED = 'GET_ALL_CHARACTERS_FULFILLED'
export const GET_ALL_CHARACTERS_REJECTED = 'GET_ALL_CHARACTERS_REJECTED'

export const GET_ALL_EPISODES = 'GET_ALL_EPISODES'
export const GET_ALL_EPISODES_PENDING = 'GET_ALL_EPISODES_PENDING'
export const GET_ALL_EPISODES_FULFILLED = 'GET_ALL_EPISODES_FULFILLED'
export const GET_ALL_EPISODES_REJECTED = 'GET_ALL_EPISODES_REJECTED'